name: Simpler Workflow Test
on:
  push:
    branches:
      - dev
      - staging
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"


# name: Frontend Deployment
#
# on:
#   # push:
#   #   branches:
#   #     - main
#   #     - staging
#   workflow_run:
#     workflows: ["Frontend CI"]
#     branches:
#       - main
#       - staging
#     types:
#       - completed
#
# env:
#   BUILD_ENV: ${{
#     github.event.workflow_run.head_branch == 'main' && 'main' ||
#     github.event.workflow_run.head_branch == 'staging' && 'staging'
#     }}
#
# jobs:
#   deploy-frontend:
#     # if: |
#     #   github.event.workflow_run.conclusion == 'success' && 
#     #   (github.event.workflow_run.head_branch == 'main' || 
#     #    github.event.workflow_run.head_branch == 'staging')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v4
#         # with:
#         #   ref: ${{ github.event.workflow_run.head_branch }}
#       - name: Install SSH Client
#         run: sudo apt-get install openssh-client
#       - name: Set up SSH keys
#         run: |
#           echo "${{ secrets.SSH_KEY }}" > ssh-key.pem
#           chmod 400 ssh-key.pem
#       - name: Deploy to frontend
#         run: |
#           ssh -o StrictHostKeyChecking=no -i ./ssh-key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} BUILD_ENV=${{ env.BUILD_ENV }} "
#             REPO_DIR="/home/${{ secrets.SSH_USER }}/fin-dashboard-app-team7/"
#             
#             cd \$REPO_DIR
#             git fetch
#             git checkout \$BUILD_ENV
#             git pull origin \$BUILD_ENV
#
#             cd \$REPO_DIR/frontend
#
#             npm install
#             npm run build
#
#             case "\$BUILD_ENV" in
#               "main") export FRONTEND_PORT=80 ;;
#               "staging") export FRONTEND_PORT=3002 ;;
#               *) export FRONTEND_PORT=8080 ;;
#             esac
#
#             pm2 delete frontend-\${BUILD_ENV} || true
#             PORT=\$FRONTEND_PORT pm2 start npm --name frontend-\${BUILD_ENV} -- run start"
