name: Frontend Deployment

on:
  push:
    branches:
      - main
      - staging

env:
  BUILD_ENV: ${{
    github.ref_name == 'main' && 'main' ||
    github.ref_name == 'staging' && 'staging
    }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: frontend-ci
    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh-key.pem
          chmod 600 ssh-key.pem
      - name: Deploy to frontend
        run: |
          ssh -i ssh-key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} BUILD_ENV=${{ env.BUILD_ENV }} << 'EOF'
          set -e

          REPO_DIR="$HOME/fin-dashboard-app-team7/"
          
          cd $REPO_DIR
          git checkout $BUILD_ENV
          git pull origin $BUILD_ENV

          cd $REPO_DIR/frontend

          npm install
          npm run build

          case "$BUILD_ENV" in
            "main") export FRONTEND_PORT=80 ;;
            "staging") export FRONTEND_PORT=3002 ;;
            *) export FRONTEND_PORT=8080 ;;
          esac

          pm2 delete frontend-${BUILD_ENV} || true
          PORT=$FRONTEND_PORT pm2 start npm --name frontend-${BUILD_ENV} -- run start
 
